# Generated by Django 3.0.5 on 2020-06-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('icon', models.ImageField(upload_to='pic')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bill_categories',
            },
        ),
        migrations.CreateModel(
            name='Bill_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField()),
                ('landowner_id', models.IntegerField()),
                ('bill_category_id', models.IntegerField()),
                ('bill_category_name', models.CharField(max_length=255)),
                ('bill_amount', models.FloatField()),
                ('form_date', models.IntegerField()),
                ('to_date', models.IntegerField()),
                ('payment_date', models.IntegerField()),
                ('receipt_image', models.ImageField(upload_to='bill')),
                ('note', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'bills',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
