# Generated by Django 3.0.5 on 2020-05-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landowner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
